#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# include all the modules used by this profile
mod 'puppetlabs-stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git'
mod 'stahnma-epel'